# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\clue_text\window\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.question = QtWidgets.QTextEdit(self.centralwidget)
        self.question.setGeometry(QtCore.QRect(110, 40, 501, 81))
        self.question.setObjectName("question")
        self.answer = QtWidgets.QTextEdit(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(110, 150, 501, 391))
        self.answer.setReadOnly(True)
        self.answer.setObjectName("answer")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 300, 61, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(660, 50, 111, 61))
        self.submit.setObjectName("submit")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(680, 500, 81, 41))
        self.exit.setObjectName("exit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "输入："))
        self.label_2.setText(_translate("MainWindow", "回答："))
        self.submit.setText(_translate("MainWindow", "发送"))
        self.exit.setText(_translate("MainWindow", "退出"))
